#
#################################################################################
#
#  Copyright (c) 2021 CertifAI Sdn. Bhd.
#
#  This program is part of OSRFramework. You can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#################################################################################
#

global:
  scrape_interval: 1s

scrape_configs:

  - job_name: "prometheus"

    static_configs:
      ##### CHANGE HERE
      - targets: ["localhost:9090"]

  - job_name: "node_exporter"

    static_configs:
      - targets: ["node:9100"]

  - job_name: "model_server"

    static_configs:
      ##### CHANGE HERE
      - targets: ["model_server:8000"]

  - job_name: 'drift_detector'

    static_configs:
      ##### CHANGE HERE
      - targets: ["drift_detector_server:8009"]