{
 "title": "Model Monitoring Dashboard (Linux)",
 "tags": [
  "linux",
  "node_exporter"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   { "name": "diskdevices", "query": "[a-z]+|nvme[0-9]+n[0-9]+" }
  ]
 },
 "panels": [
  {
   "title": "Current Date and Time (YYYY-MM-DD 24H)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "time()" }
   ]
  },
  { "title": "Operation Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 6 },
   "options": {
    "content": "<center><h1>Request Throughput</h1></center>\n</br>\n<h5>2xx status codes denote a successful model\nprediction.\n\n4xx status codes are common when clients\nPOST data that does not meet the expected\nschema.\n\nWe calculate the success rate as the percentage\nof HTTP requests that do not return a 5xx code.</h5>"
   }
  },
  {
   "title": "HTTP Success Rate (1m avg)",
   "type": "gauge",
   "description": "Percentage of requests that returned 2xx and 4xx status codes.",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(fastapi_requests_total{status_code!=\"500\"}[1m]))/sum(rate(fastapi_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Rate of Requests",
   "type": "timeseries",
   "description": "Rate of requests by status code.",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(fastapi_requests_total[1m])) by (status_code)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 14 },
   "options": {
    "content": "<center>\n  <h1>\n  Request Latencies\n  </h1>\n</center></br>\n\n<h5>\nWe have two SLOs for API latency:</br>\n\n- Average latency SLO is breached if p50 latencies exceed 50ms for 5 minutes.\n- Extreme latency SLO is breached if p99 latencies exceed 300ms for 5 minutes.\n</h5>"
   }
  },
  {
   "title": "Requests In Progress",
   "type": "stat",
   "description": "Total number of requests being processed at the moment.",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(fastapi_request_in_progress{path!=\"/favicon.ico\"})",
     "legendFormat": "/, /predict, /metrics"
    }
   ]
  },
  {
   "title": "Server Latency",
   "type": "timeseries",
   "description": "The amount of time taken for all endpoints in the API to respond, on average.",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n  sum(\n    rate(fastapi_request_duration_seconds_bucket[1m]))\n  by (le)\n)",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95,\n  sum(\n    rate(fastapi_request_duration_seconds_bucket[1m]))\n  by (le)\n)",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50,\n  sum(\n    rate(fastapi_request_duration_seconds_bucket[1m]))\n  by (le)\n)",
     "legendFormat": "50th Percentile"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 22 },
   "options": {
    "content": "<center>\n  <h1>\n  Total Requests\n  </h1>\n</center></br>\n\n<h5>\nIn some use cases, it may be important to know the total number of hits to a certain endpoint.</br>\n</h5>"
   }
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (path) (fastapi_requests_total{status_code !=\"500\", path!=\"/metrics\"})",
     "legendFormat": "Endpoint: {{path}}"
    }
   ]
  },
  { "title": "Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Processors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 31 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{}) by (cpu))"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{}) /  count(count(node_cpu_seconds_total{}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-((node_memory_MemAvailable_bytes{}*100)/node_memory_MemTotal_bytes{})"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user'}[$__rate_interval])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait'}[$__rate_interval])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle'}[$__rate_interval])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 31 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 34 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes{}" }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_SwapTotal_bytes{}" }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{} - node_memory_SwapFree_bytes{}) / (node_memory_SwapTotal_bytes{} )) * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/etc/hosts\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/etc/hosts\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemTotal_bytes{}", "legendFormat": "RAM Total" },
    {
     "expr": "node_memory_MemTotal_bytes{} - node_memory_MemFree_bytes{} - (node_memory_Cached_bytes{} + node_memory_Buffers_bytes{})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{} + node_memory_Buffers_bytes{}",
     "legendFormat": "RAM Cache + Buffer"
    },
    { "expr": "node_memory_MemFree_bytes{}", "legendFormat": "RAM Free" },
    {
     "expr": "(node_memory_SwapTotal_bytes{} - node_memory_SwapFree_bytes{})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 38 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/etc/hosts\",fstype!=\"rootfs\"}"
    }
   ]
  },
  { "title": "Model Performance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 46 },
   "options": {
    "content": "<center>\n  <h1>\n  Prediction Latencies\n  </h1>\n</center></br>\n\n<h5>\nWe have two SLOs for Prediction latency:</br>\n\n- Average latency SLO is breached if p50 latencies exceed 50ms for 5 minutes.\n- Extreme latency SLO is breached if p99 latencies exceed 300ms for 5 minutes.\n</h5>"
   }
  },
  {
   "title": "Predictions Requests In Progress",
   "type": "stat",
   "description": "Total number of prediction requests being processed at the moment.",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "fastapi_request_in_progress{path = \"/predict\"}"
    }
   ]
  },
  {
   "title": "Inference Latency",
   "type": "timeseries",
   "description": "The amount of time taken for prediction endpoint in the API to respond.",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n  sum(\n    rate(fastapi_request_duration_seconds_bucket{path=\"/predict\"}[1m]))\n  by (le)\n)",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95,\n  sum(\n    rate(fastapi_request_duration_seconds_bucket{path=\"/predict\"}[1m]))\n  by (le)\n)",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50,\n  sum(\n    rate(fastapi_request_duration_seconds_bucket{path=\"/predict\"}[1m]))\n  by (le)\n)",
     "legendFormat": "50th Percentile"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 54 },
   "options": {
    "content": "<center>\n  <h1>\n  Prediction Distribution\n  </h1>\n</center></br>\n\n<h5>\nThis prediction distribution shows the percentage of each predicted class against all predictions.\n</h5>"
   }
  },
  {
   "title": "Prediction Distribution",
   "type": "gauge",
   "description": "Percentage of predicted class over total predictions",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prediction_total{class=\"lemon\"})/sum(fastapi_requests_total{status_code=\"200\", path=\"/predict\"})*100",
     "legendFormat": "Class: lemon"
    },
    {
     "expr": "sum(prediction_total{class=\"apple\"})/sum(fastapi_requests_total{status_code=\"200\", path=\"/predict\"})*100",
     "legendFormat": "Class: apple"
    },
    {
     "expr": "sum(prediction_total{class=\"grapes\"})/sum(fastapi_requests_total{status_code=\"200\", path=\"/predict\"})*100",
     "legendFormat": "Class: grapes"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 62 },
   "options": {
    "content": "<center>\n  <h1>\n  P-Value\n  </h1>\n</center></br>\n\n<h5>\nThis metric is useful in determining if a drift was detected in the input data.</br>\n</br>\n<span style=\"color:red\">Red value</span> indicates drift. (Scaled up by 1x10^2)\n</h5>"
   }
  },
  {
   "title": "P-Values",
   "type": "stat",
   "description": "Red indicates Drift.",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "drift_detector_pvalue{value=\"current_p_value\"}*1e2",
     "legendFormat": "p-value"
    }
   ]
  },
  {
   "title": "P-Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "drift_detector_pvalue{value=\"current_p_value\"}*1e2",
     "legendFormat": "p-value"
    }
   ]
  }
 ]
}