#
#################################################################################
#
#  Copyright (c) 2021 CertifAI Sdn. Bhd.
#
#  This program is part of OSRFramework. You can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#################################################################################
#

version: "3.9"

services:
  mongodb:
    image: 'mongo:4.4-bionic'
    container_name: 'mongodb'
    restart: 'always'
    
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_USERNAME=admin
      - MONGO_INITDB_PASSWORD=admin
      - MONGO_INITDB_DATABASE=drift_detection
    volumes:
      - './mongo_data:/data/db'
      - './mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js'
    ports:
      - '27017:27017'
volumes:
    mongo_data:
